import 'dart:typed_data';

import 'package:elsafe/config/temuan_model.dart';
import 'package:elsafe/utils/pdf_generator.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('ExportTemuanPdfGenerator', () {
    test('uses the requested report title', () {
      expect(
        ExportTemuanPdfGenerator.reportTitle,
        'TEMUAN POTENSI KMU / ROW - GENERATED BY ELSAFE',
      );
    });

    test('generates a valid PDF document for selected findings', () async {
      final bytes = await ExportTemuanPdfGenerator.generate(
        temuan: [
          TemuanModel(
            id: '1',
            lokasi: 'Gardu Induk A',
            namaPemilik: 'PLN',
            tanggalTemuan: DateTime(2026, 5, 5),
            statusTemuan: 'Open',
            levelRisiko: 'Tinggi',
            namaPenyulang: 'Penyulang A',
            zona: 1,
            section: 2,
            ulp: 'ULP A',
            deskripsiTemuan: 'ROW terlalu dekat',
          ),
        ],
        generatedAt: DateTime(2026, 5, 6, 10, 30),
        logoAssetLoader: (_) async => ByteData(0),
      );

      expect(bytes.length, greaterThan(1000));
      expect(String.fromCharCodes(bytes.take(5)), '%PDF-');
    });
  });
}
