import 'dart:typed_data';

import 'package:http/http.dart' as http;
import 'package:syncfusion_flutter_xlsio/xlsio.dart' as xlsio;

import '../config/temuan_model.dart';

typedef NetworkImageLoader = Future<Uint8List?> Function(String url);

class ExportTemuanExcelGenerator {
  static const reportTitle = 'TEMUAN POTENSI KMU / ROW - GENERATED BY ELSAFE';
  static const _plnBlue = '#0B5CAB';
  static const _plnBlueDark = '#083F7A';
  static const _white = '#FFFFFF';
  static const _lightBlue = '#EFF6FF';
  static const _lightGray = '#F8FAFC';
  static const _borderGray = '#E2E8F0';
  static const _textBlue = '#2563EB';
  static const _green = '#DCFCE7';
  static const _amber = '#FEF3C7';
  static const _orange = '#F97316';
  static const _red = '#DC2626';

  static Future<Uint8List> generate({
    required List<TemuanModel> temuan,
    DateTime? startDate,
    DateTime? endDate,
    String? ulpLabel,
    DateTime? generatedAt,
    NetworkImageLoader? networkImageLoader,
  }) async {
    final createdAt = (generatedAt ?? DateTime.now()).toLocal();
    final imageLoader = networkImageLoader ?? _loadNetworkImage;
    final photoRows = <_PhotoRow>[];
    for (final item in temuan) {
      photoRows.add(
        _PhotoRow(
          temuan: await _loadPhoto(item.fotoUrls, imageLoader),
          reminder: await _loadPhoto(item.fotoReminder, imageLoader),
          closing: await _loadPhoto(item.fotoClosing, imageLoader),
        ),
      );
    }

    final workbook = xlsio.Workbook();
    try {
      final temuanSheet = workbook.worksheets[0];
      temuanSheet.name = 'Temuan';
      final summarySheet = workbook.worksheets.addWithName('Ringkasan');

      _writeTemuanSheet(
        temuanSheet,
        temuan: temuan,
        photoRows: photoRows,
        startDate: startDate,
        endDate: endDate,
        ulpLabel: ulpLabel,
        generatedAt: createdAt,
      );
      _writeSummarySheet(
        summarySheet,
        temuan: temuan,
        startDate: startDate,
        endDate: endDate,
        ulpLabel: ulpLabel,
        generatedAt: createdAt,
      );

      return Uint8List.fromList(workbook.saveAsStream());
    } finally {
      workbook.dispose();
    }
  }

  static void _writeTemuanSheet(
    xlsio.Worksheet sheet, {
    required List<TemuanModel> temuan,
    required List<_PhotoRow> photoRows,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
    required DateTime generatedAt,
  }) {
    _writeText(sheet, 1, 1, reportTitle);
    _writeText(sheet, 2, 1, 'Periode');
    _writeText(sheet, 2, 2, _periodLabel(startDate, endDate));
    _writeText(sheet, 3, 1, 'ULP');
    _writeText(sheet, 3, 2, _valueOrDash(ulpLabel));
    _writeText(sheet, 4, 1, 'Generated at');
    _writeText(sheet, 4, 2, _formatDateTime(generatedAt));

    for (var i = 0; i < _headers.length; i++) {
      _writeText(sheet, 6, i + 1, _headers[i]);
    }

    for (var i = 0; i < temuan.length; i++) {
      final row = i + 7;
      final item = temuan[i];
      final photoRow = photoRows[i];
      _writeNumber(sheet, row, 1, i + 1);
      _writeText(sheet, row, 2, _formatDate(item.tanggalTemuan));
      _writeText(sheet, row, 3, _valueOrDash(item.ulp));
      _writeText(sheet, row, 4, _valueOrDash(item.tipeTemuan));
      _writeText(sheet, row, 5, _valueOrDash(item.alamatTemuan));
      _writeText(sheet, row, 6, _valueOrDash(item.lokasi));
      _writeText(sheet, row, 7, _mapsUrl(item));
      _writeText(sheet, row, 8, _coordinates(item));
      _writeText(sheet, row, 9, _pemilikObjekLabel(item));
      _writeText(sheet, row, 10, _valueOrDash(item.namaPenyulang));
      _writeText(sheet, row, 11, item.zona?.toString() ?? '-');
      _writeText(sheet, row, 12, item.section?.toString() ?? '-');
      _writeText(sheet, row, 13, _valueOrDash(item.levelRisiko));
      _writeText(sheet, row, 14, _valueOrDash(item.statusTemuan));
      _writeText(sheet, row, 15, _tindakLanjutLabel(item));
      _writePhotoCell(sheet, row, 16, photoRow.temuan);
      _writePhotoCell(sheet, row, 17, photoRow.reminder);
      _writePhotoCell(sheet, row, 18, photoRow.closing);
    }

    _styleTemuanSheet(sheet, temuan.length);
    _setTemuanColumnWidths(sheet);
  }

  static void _writeSummarySheet(
    xlsio.Worksheet sheet, {
    required List<TemuanModel> temuan,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
    required DateTime generatedAt,
  }) {
    _writeText(sheet, 1, 1, reportTitle);
    _writeText(sheet, 2, 1, 'Periode');
    _writeText(sheet, 2, 2, _periodLabel(startDate, endDate));
    _writeText(sheet, 3, 1, 'ULP');
    _writeText(sheet, 3, 2, _valueOrDash(ulpLabel));
    _writeText(sheet, 4, 1, 'Generated at');
    _writeText(sheet, 4, 2, _formatDateTime(generatedAt));

    _appendKpiCards(sheet, temuan, startRow: 6);
    _writeText(sheet, 9, 1, 'Ringkasan');
    _writeText(sheet, 9, 2, 'Jumlah');
    _writeText(sheet, 10, 1, 'Total temuan dipilih');
    _writeNumber(sheet, 10, 2, temuan.length);

    var nextRow = 12;
    nextRow = _appendBreakdown(
      sheet,
      nextRow,
      'Status',
      _countBy(temuan, (item) => item.statusTemuan),
    );
    nextRow++;
    nextRow = _appendBreakdown(
      sheet,
      nextRow,
      'Risiko',
      _countBy(temuan, (item) => item.levelRisiko),
    );

    final ulpCounts = _countBy(temuan, (item) => item.ulp);
    if (ulpCounts.length > 1) {
      nextRow++;
      _appendBreakdown(sheet, nextRow, 'ULP', ulpCounts);
    }

    _styleSummarySheet(sheet);
  }

  static void _appendKpiCards(
    xlsio.Worksheet sheet,
    List<TemuanModel> temuan, {
    required int startRow,
  }) {
    final statusCounts = _countBy(temuan, (item) => item.statusTemuan);
    final riskCounts = _countBy(temuan, (item) => item.levelRisiko);
    final openCount = statusCounts['Open'] ?? 0;
    final closedCount =
        (statusCounts['Closed'] ?? 0) + (statusCounts['Close'] ?? 0);
    final priorityCount =
        (riskCounts['Extreme'] ?? 0) +
        (riskCounts['High'] ?? 0) +
        (riskCounts['Tinggi'] ?? 0);

    final labels = ['TOTAL', 'OPEN', 'CLOSED', 'EXTREME/HIGH'];
    final values = [temuan.length, openCount, closedCount, priorityCount];
    final columns = [1, 3, 5, 7];

    for (var i = 0; i < labels.length; i++) {
      _writeText(sheet, startRow, columns[i], labels[i]);
      _writeNumber(sheet, startRow + 1, columns[i], values[i]);
    }
  }

  static int _appendBreakdown(
    xlsio.Worksheet sheet,
    int startRow,
    String label,
    Map<String, int> counts,
  ) {
    _writeText(sheet, startRow, 1, label);
    _writeText(sheet, startRow, 2, 'Jumlah');
    var row = startRow + 1;
    if (counts.isEmpty) {
      _writeText(sheet, row, 1, '-');
      _writeNumber(sheet, row, 2, 0);
      return row + 1;
    }
    for (final entry in counts.entries) {
      _writeText(sheet, row, 1, entry.key);
      _writeNumber(sheet, row, 2, entry.value);
      row++;
    }
    return row;
  }

  static Map<String, int> _countBy(
    List<TemuanModel> temuan,
    String? Function(TemuanModel item) selector,
  ) {
    final counts = <String, int>{};
    for (final item in temuan) {
      final key = _valueOrDash(selector(item));
      counts[key] = (counts[key] ?? 0) + 1;
    }
    return counts;
  }

  static void _writePhotoCell(
    xlsio.Worksheet sheet,
    int row,
    int column,
    _PhotoCell photo,
  ) {
    if (photo.isEmpty) {
      _writeText(sheet, row, column, '-');
      return;
    }
    if (photo.bytes == null) {
      _writeText(sheet, row, column, photo.firstUrl);
      return;
    }

    _writeText(sheet, row, column, photo.remainingLabel);
    final picture = sheet.pictures.addStream(row, column, photo.bytes!);
    picture.width = 54;
    picture.height = 42;
  }

  static Future<_PhotoCell> _loadPhoto(
    List<String>? urls,
    NetworkImageLoader imageLoader,
  ) async {
    final filtered =
        urls
            ?.map((url) => url.trim())
            .where((url) => url.isNotEmpty)
            .toList() ??
        const <String>[];
    if (filtered.isEmpty) return const _PhotoCell.empty();

    Uint8List? bytes;
    try {
      bytes = await imageLoader(filtered.first);
    } catch (_) {
      bytes = null;
    }
    if (bytes != null && bytes.isEmpty) bytes = null;
    return _PhotoCell(
      firstUrl: filtered.first,
      count: filtered.length,
      bytes: bytes,
    );
  }

  static Future<Uint8List?> _loadNetworkImage(String url) async {
    try {
      final response = await http.get(Uri.parse(url));
      if (response.statusCode != 200 || response.bodyBytes.isEmpty) {
        return null;
      }
      return response.bodyBytes;
    } catch (_) {
      return null;
    }
  }

  static void _setTemuanColumnWidths(xlsio.Worksheet sheet) {
    const widths = <int, int>{
      1: 52,
      2: 88,
      3: 120,
      4: 96,
      5: 220,
      6: 180,
      7: 250,
      8: 150,
      9: 180,
      10: 140,
      11: 64,
      12: 64,
      13: 90,
      14: 100,
      15: 140,
      16: 92,
      17: 92,
      18: 92,
    };

    for (final entry in widths.entries) {
      sheet.setColumnWidthInPixels(entry.key, entry.value);
    }
  }

  static void _styleTemuanSheet(xlsio.Worksheet sheet, int dataCount) {
    _merge(sheet, 1, 1, 1, 18, _titleStyle);
    _styleRow(sheet, 2, 1, 2, _metaLabelStyle);
    _styleRow(sheet, 3, 1, 2, _metaLabelStyle);
    _styleRow(sheet, 4, 1, 2, _metaLabelStyle);
    _styleRow(sheet, 6, 1, _headers.length, _headerStyle);
    sheet.setRowHeightInPixels(1, 34);
    sheet.setRowHeightInPixels(6, 36);

    for (var row = 7; row < 7 + dataCount; row++) {
      final fillStyle = row.isEven ? _bodyAltStyle : _bodyStyle;
      _styleRow(sheet, row, 1, _headers.length, fillStyle);
      sheet.setRowHeightInPixels(row, 70);

      final riskText = _cellText(sheet, row, 13);
      final statusText = _cellText(sheet, row, 14);
      _applyStyle(sheet.getRangeByIndex(row, 13), _riskStyle(riskText));
      _applyStyle(sheet.getRangeByIndex(row, 14), _statusStyle(statusText));

      if (_cellText(sheet, row, 7) != '-') {
        _applyStyle(sheet.getRangeByIndex(row, 7), _linkStyle);
      }
      for (final column in [16, 17, 18]) {
        _applyStyle(sheet.getRangeByIndex(row, column), _photoStyle);
      }
    }
  }

  static void _styleSummarySheet(xlsio.Worksheet sheet) {
    _merge(sheet, 1, 1, 1, 8, _titleStyle);
    _styleRow(sheet, 2, 1, 2, _metaLabelStyle);
    _styleRow(sheet, 3, 1, 2, _metaLabelStyle);
    _styleRow(sheet, 4, 1, 2, _metaLabelStyle);
    sheet.setRowHeightInPixels(1, 34);

    for (final column in [1, 3, 5, 7]) {
      _applyStyle(sheet.getRangeByIndex(6, column), _kpiLabelStyle);
      _applyStyle(sheet.getRangeByIndex(7, column), _kpiValueStyle);
      sheet.setColumnWidthInPixels(column, 120);
    }
    sheet.setColumnWidthInPixels(2, 72);
    sheet.setColumnWidthInPixels(4, 72);
    sheet.setColumnWidthInPixels(6, 72);
    sheet.setColumnWidthInPixels(8, 72);
    sheet.setColumnWidthInPixels(1, 150);

    for (var row = 9; row <= 80; row++) {
      final first = _cellText(sheet, row, 1);
      final second = _cellText(sheet, row, 2);
      if (first.isEmpty && second.isEmpty) continue;
      if (second == 'Jumlah') {
        _styleRow(sheet, row, 1, 2, _sectionHeaderStyle);
      } else if (first != '-') {
        _styleRow(sheet, row, 1, 2, row.isEven ? _bodyAltStyle : _bodyStyle);
      }
    }
  }

  static void _styleRow(
    xlsio.Worksheet sheet,
    int row,
    int startColumn,
    int endColumn,
    _StyleSpec style,
  ) {
    for (var column = startColumn; column <= endColumn; column++) {
      _applyStyle(sheet.getRangeByIndex(row, column), style);
    }
  }

  static void _merge(
    xlsio.Worksheet sheet,
    int startRow,
    int startColumn,
    int endRow,
    int endColumn,
    _StyleSpec style,
  ) {
    final range = sheet.getRangeByIndex(
      startRow,
      startColumn,
      endRow,
      endColumn,
    );
    range.merge();
    _applyStyle(range, style);
  }

  static void _writeText(
    xlsio.Worksheet sheet,
    int row,
    int column,
    String value,
  ) {
    sheet.getRangeByIndex(row, column).setText(value);
  }

  static void _writeNumber(
    xlsio.Worksheet sheet,
    int row,
    int column,
    num value,
  ) {
    sheet.getRangeByIndex(row, column).setNumber(value.toDouble());
  }

  static String _cellText(xlsio.Worksheet sheet, int row, int column) {
    final value = sheet.getRangeByIndex(row, column).text;
    return value?.toString() ?? '';
  }

  static void _applyStyle(xlsio.Range range, _StyleSpec spec) {
    final style = range.cellStyle;
    style.bold = spec.bold;
    if (spec.fontSize != null) style.fontSize = spec.fontSize!;
    if (spec.fontColor != null) style.fontColor = spec.fontColor!;
    if (spec.backColor != null) style.backColor = spec.backColor!;
    if (spec.hAlign != null) style.hAlign = spec.hAlign!;
    if (spec.vAlign != null) style.vAlign = spec.vAlign!;
    style.wrapText = spec.wrapText;
    if (spec.underline) style.underline = true;
  }

  static const _titleStyle = _StyleSpec(
    bold: true,
    fontSize: 15,
    fontColor: _white,
    backColor: _plnBlue,
    hAlign: xlsio.HAlignType.center,
    vAlign: xlsio.VAlignType.center,
  );

  static const _metaLabelStyle = _StyleSpec(
    bold: true,
    fontColor: _plnBlueDark,
    backColor: _lightBlue,
    vAlign: xlsio.VAlignType.center,
  );

  static const _headerStyle = _StyleSpec(
    bold: true,
    fontColor: _white,
    backColor: _plnBlue,
    hAlign: xlsio.HAlignType.center,
    vAlign: xlsio.VAlignType.center,
    wrapText: true,
  );

  static const _bodyStyle = _StyleSpec(
    backColor: _white,
    vAlign: xlsio.VAlignType.center,
    wrapText: true,
  );

  static const _bodyAltStyle = _StyleSpec(
    backColor: _lightGray,
    vAlign: xlsio.VAlignType.center,
    wrapText: true,
  );

  static const _photoStyle = _StyleSpec(
    backColor: _white,
    hAlign: xlsio.HAlignType.center,
    vAlign: xlsio.VAlignType.bottom,
    wrapText: true,
  );

  static const _linkStyle = _StyleSpec(
    fontColor: _textBlue,
    backColor: _white,
    vAlign: xlsio.VAlignType.center,
    wrapText: true,
    underline: true,
  );

  static _StyleSpec _riskStyle(String value) {
    final normalized = value.trim().toLowerCase();
    if (normalized == 'extreme') {
      return const _StyleSpec(
        bold: true,
        fontColor: _white,
        backColor: _red,
        hAlign: xlsio.HAlignType.center,
        vAlign: xlsio.VAlignType.center,
        wrapText: true,
      );
    }
    if (normalized == 'high' || normalized == 'tinggi') {
      return const _StyleSpec(
        bold: true,
        fontColor: _white,
        backColor: _orange,
        hAlign: xlsio.HAlignType.center,
        vAlign: xlsio.VAlignType.center,
        wrapText: true,
      );
    }
    if (normalized == 'medium' ||
        normalized == 'sedang' ||
        normalized == 'rendah') {
      return const _StyleSpec(
        bold: true,
        backColor: _amber,
        hAlign: xlsio.HAlignType.center,
        vAlign: xlsio.VAlignType.center,
        wrapText: true,
      );
    }
    return const _StyleSpec(
      backColor: _borderGray,
      hAlign: xlsio.HAlignType.center,
      vAlign: xlsio.VAlignType.center,
      wrapText: true,
    );
  }

  static _StyleSpec _statusStyle(String value) {
    final normalized = value.trim().toLowerCase();
    if (normalized == 'closed' || normalized == 'close') {
      return const _StyleSpec(
        bold: true,
        backColor: _green,
        hAlign: xlsio.HAlignType.center,
        vAlign: xlsio.VAlignType.center,
        wrapText: true,
      );
    }
    if (normalized == 'open') {
      return const _StyleSpec(
        bold: true,
        backColor: _amber,
        hAlign: xlsio.HAlignType.center,
        vAlign: xlsio.VAlignType.center,
        wrapText: true,
      );
    }
    return const _StyleSpec(
      bold: true,
      backColor: _lightBlue,
      hAlign: xlsio.HAlignType.center,
      vAlign: xlsio.VAlignType.center,
      wrapText: true,
    );
  }

  static const _kpiLabelStyle = _StyleSpec(
    bold: true,
    fontColor: _white,
    backColor: _plnBlue,
    hAlign: xlsio.HAlignType.center,
    vAlign: xlsio.VAlignType.center,
  );

  static const _kpiValueStyle = _StyleSpec(
    bold: true,
    fontSize: 18,
    fontColor: _plnBlueDark,
    backColor: _lightBlue,
    hAlign: xlsio.HAlignType.center,
    vAlign: xlsio.VAlignType.center,
  );

  static const _sectionHeaderStyle = _StyleSpec(
    bold: true,
    fontColor: _white,
    backColor: _plnBlueDark,
    vAlign: xlsio.VAlignType.center,
  );

  static final List<String> _headers = [
    'No',
    'Tanggal',
    'ULP',
    'Tipe',
    'Alamat Temuan',
    'Lokasi',
    'Link Maps',
    'Koordinat',
    'Pemilik / Objek',
    'Penyulang',
    'Zona',
    'Section',
    'Risiko',
    'Status',
    'Tindak Lanjut',
    'Foto Temuan',
    'Foto Reminder',
    'Foto Closing',
  ];

  static String _periodLabel(DateTime? startDate, DateTime? endDate) {
    if (startDate == null && endDate == null) return 'Semua periode';
    if (startDate != null && endDate != null) {
      return '${_formatDate(startDate)} - ${_formatDate(endDate)}';
    }
    if (startDate != null) return 'Mulai ${_formatDate(startDate)}';
    return 'Sampai ${_formatDate(endDate!)}';
  }

  static String _formatDate(DateTime date) {
    final day = date.day.toString().padLeft(2, '0');
    final month = date.month.toString().padLeft(2, '0');
    return '$day/$month/${date.year}';
  }

  static String _formatDateTime(DateTime date) {
    final hour = date.hour.toString().padLeft(2, '0');
    final minute = date.minute.toString().padLeft(2, '0');
    return '${_formatDate(date)} $hour:$minute';
  }

  static String _valueOrDash(String? value) {
    if (value == null || value.trim().isEmpty) return '-';
    return value.trim();
  }

  static String _joinNonEmpty(List<String?> values) {
    final filtered =
        values
            .where((value) => value != null && value.trim().isNotEmpty)
            .map((value) => value!.trim())
            .toList();
    if (filtered.isEmpty) return '-';
    return filtered.join(' / ');
  }

  static String _coordinates(TemuanModel item) {
    final latitude = item.latitude;
    final longitude = item.longitude;
    if (latitude == null || longitude == null) return '-';
    return '$latitude, $longitude';
  }

  static String _mapsUrl(TemuanModel item) {
    final latitude = item.latitude;
    final longitude = item.longitude;
    if (latitude == null || longitude == null) return '-';
    return 'https://www.google.com/maps/search/?api=1&query=$latitude,$longitude';
  }

  static String _pemilikObjekLabel(TemuanModel item) {
    return _joinNonEmpty([item.namaPemilik, item.jenisObjek, item.jenisAset]);
  }

  static String _tindakLanjutLabel(TemuanModel item) {
    if (item.tglClosing != null) {
      return 'Closed: ${_formatDate(item.tglClosing!)}';
    }
    if (item.tglReminder != null) {
      return 'Reminder: ${_formatDate(item.tglReminder!)}';
    }
    return '-';
  }
}

class _PhotoRow {
  const _PhotoRow({
    required this.temuan,
    required this.reminder,
    required this.closing,
  });

  final _PhotoCell temuan;
  final _PhotoCell reminder;
  final _PhotoCell closing;
}

class _PhotoCell {
  const _PhotoCell({
    required this.firstUrl,
    required this.count,
    required this.bytes,
  });

  const _PhotoCell.empty() : firstUrl = '', count = 0, bytes = null;

  final String firstUrl;
  final int count;
  final Uint8List? bytes;

  bool get isEmpty => firstUrl.isEmpty;
  String get remainingLabel => count > 1 ? '(+${count - 1} lagi)' : '';
}

class _StyleSpec {
  const _StyleSpec({
    this.bold = false,
    this.fontSize,
    this.fontColor,
    this.backColor,
    this.hAlign,
    this.vAlign,
    this.wrapText = false,
    this.underline = false,
  });

  final bool bold;
  final double? fontSize;
  final String? fontColor;
  final String? backColor;
  final xlsio.HAlignType? hAlign;
  final xlsio.VAlignType? vAlign;
  final bool wrapText;
  final bool underline;
}
