import 'dart:typed_data';

import 'package:excel/excel.dart';

import '../config/temuan_model.dart';

class ExportTemuanExcelGenerator {
  static const reportTitle = 'TEMUAN POTENSI KMU / ROW - GENERATED BY ELSAFE';
  static final _plnBlue = ExcelColor.fromHexString('FF0B5CAB');
  static final _plnBlueDark = ExcelColor.fromHexString('FF083F7A');
  static final _white = ExcelColor.fromHexString('FFFFFFFF');
  static final _lightBlue = ExcelColor.fromHexString('FFEFF6FF');
  static final _lightGray = ExcelColor.fromHexString('FFF8FAFC');
  static final _borderGray = ExcelColor.fromHexString('FFE2E8F0');
  static final _textBlue = ExcelColor.fromHexString('FF2563EB');
  static final _green = ExcelColor.fromHexString('FFDCFCE7');
  static final _amber = ExcelColor.fromHexString('FFFEF3C7');
  static final _orange = ExcelColor.fromHexString('FFF97316');
  static final _red = ExcelColor.fromHexString('FFDC2626');

  static Uint8List generate({
    required List<TemuanModel> temuan,
    DateTime? startDate,
    DateTime? endDate,
    String? ulpLabel,
    DateTime? generatedAt,
  }) {
    final createdAt = (generatedAt ?? DateTime.now()).toLocal();
    final workbook = Excel.createExcel();

    workbook.rename('Sheet1', 'Temuan');
    final temuanSheet = workbook['Temuan'];
    final summarySheet = workbook['Ringkasan'];

    _writeTemuanSheet(
      temuanSheet,
      temuan: temuan,
      startDate: startDate,
      endDate: endDate,
      ulpLabel: ulpLabel,
      generatedAt: createdAt,
    );
    _writeSummarySheet(
      summarySheet,
      temuan: temuan,
      startDate: startDate,
      endDate: endDate,
      ulpLabel: ulpLabel,
      generatedAt: createdAt,
    );

    final encoded = workbook.encode();
    if (encoded == null) {
      throw StateError('Gagal membuat file Excel.');
    }
    return Uint8List.fromList(encoded);
  }

  static void _writeTemuanSheet(
    Sheet sheet, {
    required List<TemuanModel> temuan,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
    required DateTime generatedAt,
  }) {
    sheet.appendRow([_text(reportTitle)]);
    sheet.appendRow([
      _text('Periode'),
      _text(_periodLabel(startDate, endDate)),
    ]);
    sheet.appendRow([_text('ULP'), _text(_valueOrDash(ulpLabel))]);
    sheet.appendRow([
      _text('Generated at'),
      _text(_formatDateTime(generatedAt)),
    ]);
    sheet.appendRow(_blankRow(1));
    sheet.appendRow(_headers.map(_text).toList());

    for (var i = 0; i < temuan.length; i++) {
      final item = temuan[i];
      sheet.appendRow([
        IntCellValue(i + 1),
        _text(_formatDate(item.tanggalTemuan)),
        _text(_valueOrDash(item.ulp)),
        _text(_valueOrDash(item.tipeTemuan)),
        _text(_valueOrDash(item.alamatTemuan)),
        _text(_valueOrDash(item.lokasi)),
        _text(_mapsUrl(item)),
        _text(_coordinates(item)),
        _text(_pemilikObjekLabel(item)),
        _text(_valueOrDash(item.namaPenyulang)),
        _text(item.zona?.toString() ?? '-'),
        _text(item.section?.toString() ?? '-'),
        _text(_valueOrDash(item.levelRisiko)),
        _text(_valueOrDash(item.statusTemuan)),
        _text(_tindakLanjutLabel(item)),
        _text(_joinList(item.fotoUrls)),
        _text(_joinList(item.fotoReminder)),
        _text(_joinList(item.fotoClosing)),
      ]);
    }

    _styleTemuanSheet(sheet, temuan.length);
    _setTemuanColumnWidths(sheet);
  }

  static void _writeSummarySheet(
    Sheet sheet, {
    required List<TemuanModel> temuan,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
    required DateTime generatedAt,
  }) {
    sheet.appendRow([_text(reportTitle)]);
    sheet.appendRow([
      _text('Periode'),
      _text(_periodLabel(startDate, endDate)),
    ]);
    sheet.appendRow([_text('ULP'), _text(_valueOrDash(ulpLabel))]);
    sheet.appendRow([
      _text('Generated at'),
      _text(_formatDateTime(generatedAt)),
    ]);
    sheet.appendRow(_blankRow(1));
    _appendKpiCards(sheet, temuan);
    sheet.appendRow(_blankRow(1));
    sheet.appendRow([_text('Ringkasan'), _text('Jumlah')]);
    sheet.appendRow([
      _text('Total temuan dipilih'),
      IntCellValue(temuan.length),
    ]);
    sheet.appendRow([]);

    _appendBreakdown(
      sheet,
      'Status',
      _countBy(temuan, (item) => item.statusTemuan),
    );
    sheet.appendRow([]);
    _appendBreakdown(
      sheet,
      'Risiko',
      _countBy(temuan, (item) => item.levelRisiko),
    );

    final ulpCounts = _countBy(temuan, (item) => item.ulp);
    if (ulpCounts.length > 1) {
      sheet.appendRow([]);
      _appendBreakdown(sheet, 'ULP', ulpCounts);
    }

    _styleSummarySheet(sheet);
  }

  static void _appendKpiCards(Sheet sheet, List<TemuanModel> temuan) {
    final statusCounts = _countBy(temuan, (item) => item.statusTemuan);
    final riskCounts = _countBy(temuan, (item) => item.levelRisiko);
    final openCount = statusCounts['Open'] ?? 0;
    final closedCount =
        (statusCounts['Closed'] ?? 0) + (statusCounts['Close'] ?? 0);
    final priorityCount =
        (riskCounts['Extreme'] ?? 0) +
        (riskCounts['High'] ?? 0) +
        (riskCounts['Tinggi'] ?? 0);

    sheet.appendRow([
      _text('TOTAL'),
      _text(''),
      _text('OPEN'),
      _text(''),
      _text('CLOSED'),
      _text(''),
      _text('EXTREME/HIGH'),
    ]);
    sheet.appendRow([
      IntCellValue(temuan.length),
      _text(''),
      IntCellValue(openCount),
      _text(''),
      IntCellValue(closedCount),
      _text(''),
      IntCellValue(priorityCount),
    ]);
  }

  static void _appendBreakdown(
    Sheet sheet,
    String label,
    Map<String, int> counts,
  ) {
    sheet.appendRow([_text(label), _text('Jumlah')]);
    if (counts.isEmpty) {
      sheet.appendRow([_text('-'), IntCellValue(0)]);
      return;
    }
    for (final entry in counts.entries) {
      sheet.appendRow([_text(entry.key), IntCellValue(entry.value)]);
    }
  }

  static Map<String, int> _countBy(
    List<TemuanModel> temuan,
    String? Function(TemuanModel item) selector,
  ) {
    final counts = <String, int>{};
    for (final item in temuan) {
      final key = _valueOrDash(selector(item));
      counts[key] = (counts[key] ?? 0) + 1;
    }
    return counts;
  }

  static void _setTemuanColumnWidths(Sheet sheet) {
    const widths = <int, double>{
      0: 8,
      1: 14,
      2: 18,
      3: 14,
      4: 36,
      5: 28,
      6: 52,
      7: 24,
      8: 28,
      9: 22,
      10: 10,
      11: 10,
      12: 14,
      13: 16,
      14: 22,
      15: 42,
      16: 42,
      17: 42,
    };

    for (final entry in widths.entries) {
      sheet.setColumnWidth(entry.key, entry.value);
    }
  }

  static void _styleTemuanSheet(Sheet sheet, int dataCount) {
    _merge(sheet, 0, 0, 17, _titleStyle());
    _styleRow(sheet, 1, 0, 1, _metaLabelStyle());
    _styleRow(sheet, 2, 0, 1, _metaLabelStyle());
    _styleRow(sheet, 3, 0, 1, _metaLabelStyle());
    _styleRow(sheet, 5, 0, _headers.length - 1, _headerStyle());
    sheet.setRowHeight(0, 28);
    sheet.setRowHeight(5, 24);

    for (var row = 6; row < 6 + dataCount; row++) {
      final fillStyle = row.isEven ? _bodyStyle() : _bodyAltStyle();
      _styleRow(sheet, row, 0, _headers.length - 1, fillStyle);
      sheet.setRowHeight(row, 38);

      final riskText = _cellText(sheet, row, 12);
      final statusText = _cellText(sheet, row, 13);
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 12, rowIndex: row))
          .cellStyle = _riskStyle(riskText);
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 13, rowIndex: row))
          .cellStyle = _statusStyle(statusText);

      final mapsCell = sheet.cell(
        CellIndex.indexByColumnRow(columnIndex: 6, rowIndex: row),
      );
      if (_cellText(sheet, row, 6) != '-') {
        mapsCell.cellStyle = _linkStyle();
      }
    }
  }

  static void _styleSummarySheet(Sheet sheet) {
    _merge(sheet, 0, 0, 7, _titleStyle());
    _styleRow(sheet, 1, 0, 1, _metaLabelStyle());
    _styleRow(sheet, 2, 0, 1, _metaLabelStyle());
    _styleRow(sheet, 3, 0, 1, _metaLabelStyle());
    sheet.setRowHeight(0, 28);

    for (final column in [0, 2, 4, 6]) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: column, rowIndex: 5))
          .cellStyle = _kpiLabelStyle();
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: column, rowIndex: 6))
          .cellStyle = _kpiValueStyle();
    }

    for (var row = 8; row < sheet.maxRows; row++) {
      final first = _cellText(sheet, row, 0);
      final second = _cellText(sheet, row, 1);
      if (second == 'Jumlah') {
        _styleRow(sheet, row, 0, 1, _sectionHeaderStyle());
      } else if (first != '-') {
        _styleRow(
          sheet,
          row,
          0,
          1,
          row.isEven ? _bodyStyle() : _bodyAltStyle(),
        );
      }
    }

    const widths = <int, double>{
      0: 20,
      1: 12,
      2: 16,
      3: 4,
      4: 16,
      5: 4,
      6: 18,
      7: 4,
    };
    for (final entry in widths.entries) {
      sheet.setColumnWidth(entry.key, entry.value);
    }
  }

  static void _styleRow(
    Sheet sheet,
    int row,
    int startColumn,
    int endColumn,
    CellStyle style,
  ) {
    for (var column = startColumn; column <= endColumn; column++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: column, rowIndex: row))
          .cellStyle = style;
    }
  }

  static void _merge(
    Sheet sheet,
    int row,
    int startColumn,
    int endColumn,
    CellStyle style,
  ) {
    final start = CellIndex.indexByColumnRow(
      columnIndex: startColumn,
      rowIndex: row,
    );
    final end = CellIndex.indexByColumnRow(
      columnIndex: endColumn,
      rowIndex: row,
    );
    sheet.merge(start, end);
    sheet.setMergedCellStyle(start, style);
    sheet.cell(start).cellStyle = style;
  }

  static String _cellText(Sheet sheet, int row, int column) {
    return sheet
        .cell(CellIndex.indexByColumnRow(columnIndex: column, rowIndex: row))
        .value
        .toString();
  }

  static CellStyle _titleStyle() {
    return CellStyle(
      bold: true,
      fontSize: 15,
      fontColorHex: _white,
      backgroundColorHex: _plnBlue,
      horizontalAlign: HorizontalAlign.Center,
      verticalAlign: VerticalAlign.Center,
    );
  }

  static CellStyle _metaLabelStyle() {
    return CellStyle(
      bold: true,
      fontColorHex: _plnBlueDark,
      backgroundColorHex: _lightBlue,
      verticalAlign: VerticalAlign.Center,
    );
  }

  static CellStyle _headerStyle() {
    return CellStyle(
      bold: true,
      fontColorHex: _white,
      backgroundColorHex: _plnBlue,
      horizontalAlign: HorizontalAlign.Center,
      verticalAlign: VerticalAlign.Center,
      textWrapping: TextWrapping.WrapText,
    );
  }

  static CellStyle _bodyStyle() {
    return CellStyle(
      fontColorHex: ExcelColor.black,
      backgroundColorHex: ExcelColor.white,
      verticalAlign: VerticalAlign.Center,
      textWrapping: TextWrapping.WrapText,
    );
  }

  static CellStyle _bodyAltStyle() {
    return _bodyStyle().copyWith(backgroundColorHexVal: _lightGray);
  }

  static CellStyle _linkStyle() {
    return _bodyStyle().copyWith(
      fontColorHexVal: _textBlue,
      underlineVal: Underline.Single,
    );
  }

  static CellStyle _riskStyle(String value) {
    final normalized = value.trim().toLowerCase();
    if (normalized == 'extreme') {
      return _bodyStyle().copyWith(
        fontColorHexVal: _white,
        backgroundColorHexVal: _red,
        boldVal: true,
        horizontalAlignVal: HorizontalAlign.Center,
      );
    }
    if (normalized == 'high' || normalized == 'tinggi') {
      return _bodyStyle().copyWith(
        fontColorHexVal: _white,
        backgroundColorHexVal: _orange,
        boldVal: true,
        horizontalAlignVal: HorizontalAlign.Center,
      );
    }
    if (normalized == 'medium' ||
        normalized == 'sedang' ||
        normalized == 'rendah') {
      return _bodyStyle().copyWith(
        backgroundColorHexVal: _amber,
        boldVal: true,
        horizontalAlignVal: HorizontalAlign.Center,
      );
    }
    return _bodyStyle().copyWith(
      backgroundColorHexVal: _borderGray,
      horizontalAlignVal: HorizontalAlign.Center,
    );
  }

  static CellStyle _statusStyle(String value) {
    final normalized = value.trim().toLowerCase();
    if (normalized == 'closed' || normalized == 'close') {
      return _bodyStyle().copyWith(
        backgroundColorHexVal: _green,
        boldVal: true,
        horizontalAlignVal: HorizontalAlign.Center,
      );
    }
    if (normalized == 'open') {
      return _bodyStyle().copyWith(
        backgroundColorHexVal: _amber,
        boldVal: true,
        horizontalAlignVal: HorizontalAlign.Center,
      );
    }
    return _bodyStyle().copyWith(
      backgroundColorHexVal: _lightBlue,
      boldVal: true,
      horizontalAlignVal: HorizontalAlign.Center,
    );
  }

  static CellStyle _kpiLabelStyle() {
    return CellStyle(
      bold: true,
      fontColorHex: _white,
      backgroundColorHex: _plnBlue,
      horizontalAlign: HorizontalAlign.Center,
      verticalAlign: VerticalAlign.Center,
    );
  }

  static CellStyle _kpiValueStyle() {
    return CellStyle(
      bold: true,
      fontSize: 18,
      fontColorHex: _plnBlueDark,
      backgroundColorHex: _lightBlue,
      horizontalAlign: HorizontalAlign.Center,
      verticalAlign: VerticalAlign.Center,
    );
  }

  static CellStyle _sectionHeaderStyle() {
    return CellStyle(
      bold: true,
      fontColorHex: _white,
      backgroundColorHex: _plnBlueDark,
      verticalAlign: VerticalAlign.Center,
    );
  }

  static final List<String> _headers = [
    'No',
    'Tanggal',
    'ULP',
    'Tipe',
    'Alamat Temuan',
    'Lokasi',
    'Link Maps',
    'Koordinat',
    'Pemilik / Objek',
    'Penyulang',
    'Zona',
    'Section',
    'Risiko',
    'Status',
    'Tindak Lanjut',
    'Foto Temuan',
    'Foto Reminder',
    'Foto Closing',
  ];

  static TextCellValue _text(String value) => TextCellValue(value);

  static List<TextCellValue> _blankRow(int columns) {
    return List.generate(columns, (_) => _text(''));
  }

  static String _periodLabel(DateTime? startDate, DateTime? endDate) {
    if (startDate == null && endDate == null) return 'Semua periode';
    if (startDate != null && endDate != null) {
      return '${_formatDate(startDate)} - ${_formatDate(endDate)}';
    }
    if (startDate != null) return 'Mulai ${_formatDate(startDate)}';
    return 'Sampai ${_formatDate(endDate!)}';
  }

  static String _formatDate(DateTime date) {
    final day = date.day.toString().padLeft(2, '0');
    final month = date.month.toString().padLeft(2, '0');
    return '$day/$month/${date.year}';
  }

  static String _formatDateTime(DateTime date) {
    final hour = date.hour.toString().padLeft(2, '0');
    final minute = date.minute.toString().padLeft(2, '0');
    return '${_formatDate(date)} $hour:$minute';
  }

  static String _valueOrDash(String? value) {
    if (value == null || value.trim().isEmpty) return '-';
    return value.trim();
  }

  static String _joinList(List<String>? values) {
    if (values == null || values.isEmpty) return '-';
    final filtered = values.where((value) => value.trim().isNotEmpty).toList();
    if (filtered.isEmpty) return '-';
    return filtered.join('\n');
  }

  static String _joinNonEmpty(List<String?> values) {
    final filtered =
        values
            .where((value) => value != null && value.trim().isNotEmpty)
            .map((value) => value!.trim())
            .toList();
    if (filtered.isEmpty) return '-';
    return filtered.join(' / ');
  }

  static String _coordinates(TemuanModel item) {
    final latitude = item.latitude;
    final longitude = item.longitude;
    if (latitude == null || longitude == null) return '-';
    return '$latitude, $longitude';
  }

  static String _mapsUrl(TemuanModel item) {
    final latitude = item.latitude;
    final longitude = item.longitude;
    if (latitude == null || longitude == null) return '-';
    return 'https://www.google.com/maps/search/?api=1&query=$latitude,$longitude';
  }

  static String _pemilikObjekLabel(TemuanModel item) {
    return _joinNonEmpty([item.namaPemilik, item.jenisObjek, item.jenisAset]);
  }

  static String _tindakLanjutLabel(TemuanModel item) {
    if (item.tglClosing != null) {
      return 'Closed: ${_formatDate(item.tglClosing!)}';
    }
    if (item.tglReminder != null) {
      return 'Reminder: ${_formatDate(item.tglReminder!)}';
    }
    return '-';
  }
}
