import 'dart:typed_data';

import 'package:excel/excel.dart';

import '../config/temuan_model.dart';

class ExportTemuanExcelGenerator {
  static const reportTitle = 'TEMUAN POTENSI KMU / ROW - GENERATED BY ELSAFE';

  static Uint8List generate({
    required List<TemuanModel> temuan,
    DateTime? startDate,
    DateTime? endDate,
    String? ulpLabel,
    DateTime? generatedAt,
  }) {
    final createdAt = (generatedAt ?? DateTime.now()).toLocal();
    final workbook = Excel.createExcel();

    workbook.rename('Sheet1', 'Temuan');
    final temuanSheet = workbook['Temuan'];
    final summarySheet = workbook['Ringkasan'];

    _writeTemuanSheet(
      temuanSheet,
      temuan: temuan,
      startDate: startDate,
      endDate: endDate,
      ulpLabel: ulpLabel,
      generatedAt: createdAt,
    );
    _writeSummarySheet(
      summarySheet,
      temuan: temuan,
      startDate: startDate,
      endDate: endDate,
      ulpLabel: ulpLabel,
      generatedAt: createdAt,
    );

    final encoded = workbook.encode();
    if (encoded == null) {
      throw StateError('Gagal membuat file Excel.');
    }
    return Uint8List.fromList(encoded);
  }

  static void _writeTemuanSheet(
    Sheet sheet, {
    required List<TemuanModel> temuan,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
    required DateTime generatedAt,
  }) {
    sheet.appendRow([_text(reportTitle)]);
    sheet.appendRow([
      _text('Periode'),
      _text(_periodLabel(startDate, endDate)),
    ]);
    sheet.appendRow([_text('ULP'), _text(_valueOrDash(ulpLabel))]);
    sheet.appendRow([
      _text('Generated at'),
      _text(_formatDateTime(generatedAt)),
    ]);
    sheet.appendRow([]);
    sheet.appendRow(_headers.map(_text).toList());

    for (var i = 0; i < temuan.length; i++) {
      final item = temuan[i];
      sheet.appendRow([
        IntCellValue(i + 1),
        _text(_formatDate(item.tanggalTemuan)),
        _text(_valueOrDash(item.ulp)),
        _text(_valueOrDash(item.tipeTemuan)),
        _text(_valueOrDash(item.alamatTemuan)),
        _text(_valueOrDash(item.lokasi)),
        _text(_mapsUrl(item)),
        _text(_coordinates(item)),
        _text(_pemilikObjekLabel(item)),
        _text(_valueOrDash(item.namaPenyulang)),
        _text(item.zona?.toString() ?? '-'),
        _text(item.section?.toString() ?? '-'),
        _text(_valueOrDash(item.levelRisiko)),
        _text(_valueOrDash(item.statusTemuan)),
        _text(_tindakLanjutLabel(item)),
        _text(_joinList(item.fotoUrls)),
        _text(_joinList(item.fotoReminder)),
        _text(_joinList(item.fotoClosing)),
      ]);
    }

    _setTemuanColumnWidths(sheet);
  }

  static void _writeSummarySheet(
    Sheet sheet, {
    required List<TemuanModel> temuan,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
    required DateTime generatedAt,
  }) {
    sheet.appendRow([_text(reportTitle)]);
    sheet.appendRow([
      _text('Periode'),
      _text(_periodLabel(startDate, endDate)),
    ]);
    sheet.appendRow([_text('ULP'), _text(_valueOrDash(ulpLabel))]);
    sheet.appendRow([
      _text('Generated at'),
      _text(_formatDateTime(generatedAt)),
    ]);
    sheet.appendRow([]);
    sheet.appendRow([_text('Ringkasan'), _text('Jumlah')]);
    sheet.appendRow([
      _text('Total temuan dipilih'),
      IntCellValue(temuan.length),
    ]);
    sheet.appendRow([]);

    _appendBreakdown(
      sheet,
      'Status',
      _countBy(temuan, (item) => item.statusTemuan),
    );
    sheet.appendRow([]);
    _appendBreakdown(
      sheet,
      'Risiko',
      _countBy(temuan, (item) => item.levelRisiko),
    );

    final ulpCounts = _countBy(temuan, (item) => item.ulp);
    if (ulpCounts.length > 1) {
      sheet.appendRow([]);
      _appendBreakdown(sheet, 'ULP', ulpCounts);
    }

    sheet.setColumnWidth(0, 28);
    sheet.setColumnWidth(1, 14);
  }

  static void _appendBreakdown(
    Sheet sheet,
    String label,
    Map<String, int> counts,
  ) {
    sheet.appendRow([_text(label), _text('Jumlah')]);
    if (counts.isEmpty) {
      sheet.appendRow([_text('-'), IntCellValue(0)]);
      return;
    }
    for (final entry in counts.entries) {
      sheet.appendRow([_text(entry.key), IntCellValue(entry.value)]);
    }
  }

  static Map<String, int> _countBy(
    List<TemuanModel> temuan,
    String? Function(TemuanModel item) selector,
  ) {
    final counts = <String, int>{};
    for (final item in temuan) {
      final key = _valueOrDash(selector(item));
      counts[key] = (counts[key] ?? 0) + 1;
    }
    return counts;
  }

  static void _setTemuanColumnWidths(Sheet sheet) {
    const widths = <int, double>{
      0: 8,
      1: 14,
      2: 18,
      3: 14,
      4: 36,
      5: 28,
      6: 52,
      7: 24,
      8: 28,
      9: 22,
      10: 10,
      11: 10,
      12: 14,
      13: 16,
      14: 22,
      15: 42,
      16: 42,
      17: 42,
    };

    for (final entry in widths.entries) {
      sheet.setColumnWidth(entry.key, entry.value);
    }
  }

  static final List<String> _headers = [
    'No',
    'Tanggal',
    'ULP',
    'Tipe',
    'Alamat Temuan',
    'Lokasi',
    'Link Maps',
    'Koordinat',
    'Pemilik / Objek',
    'Penyulang',
    'Zona',
    'Section',
    'Risiko',
    'Status',
    'Tindak Lanjut',
    'Foto Temuan',
    'Foto Reminder',
    'Foto Closing',
  ];

  static TextCellValue _text(String value) => TextCellValue(value);

  static String _periodLabel(DateTime? startDate, DateTime? endDate) {
    if (startDate == null && endDate == null) return 'Semua periode';
    if (startDate != null && endDate != null) {
      return '${_formatDate(startDate)} - ${_formatDate(endDate)}';
    }
    if (startDate != null) return 'Mulai ${_formatDate(startDate)}';
    return 'Sampai ${_formatDate(endDate!)}';
  }

  static String _formatDate(DateTime date) {
    final day = date.day.toString().padLeft(2, '0');
    final month = date.month.toString().padLeft(2, '0');
    return '$day/$month/${date.year}';
  }

  static String _formatDateTime(DateTime date) {
    final hour = date.hour.toString().padLeft(2, '0');
    final minute = date.minute.toString().padLeft(2, '0');
    return '${_formatDate(date)} $hour:$minute';
  }

  static String _valueOrDash(String? value) {
    if (value == null || value.trim().isEmpty) return '-';
    return value.trim();
  }

  static String _joinList(List<String>? values) {
    if (values == null || values.isEmpty) return '-';
    final filtered = values.where((value) => value.trim().isNotEmpty).toList();
    if (filtered.isEmpty) return '-';
    return filtered.join('\n');
  }

  static String _joinNonEmpty(List<String?> values) {
    final filtered =
        values
            .where((value) => value != null && value.trim().isNotEmpty)
            .map((value) => value!.trim())
            .toList();
    if (filtered.isEmpty) return '-';
    return filtered.join(' / ');
  }

  static String _coordinates(TemuanModel item) {
    final latitude = item.latitude;
    final longitude = item.longitude;
    if (latitude == null || longitude == null) return '-';
    return '$latitude, $longitude';
  }

  static String _mapsUrl(TemuanModel item) {
    final latitude = item.latitude;
    final longitude = item.longitude;
    if (latitude == null || longitude == null) return '-';
    return 'https://www.google.com/maps/search/?api=1&query=$latitude,$longitude';
  }

  static String _pemilikObjekLabel(TemuanModel item) {
    return _joinNonEmpty([item.namaPemilik, item.jenisObjek, item.jenisAset]);
  }

  static String _tindakLanjutLabel(TemuanModel item) {
    if (item.tglClosing != null) {
      return 'Closed: ${_formatDate(item.tglClosing!)}';
    }
    if (item.tglReminder != null) {
      return 'Reminder: ${_formatDate(item.tglReminder!)}';
    }
    return '-';
  }
}
