import 'dart:typed_data';

import 'package:flutter/services.dart' show ByteData, rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../config/temuan_model.dart';

typedef LogoAssetLoader = Future<ByteData> Function(String path);

class ExportTemuanPdfGenerator {
  static const reportTitle = 'TEMUAN POTENSI KMU / ROW - GENERATED BY ELSAFE';

  static const _logoPlnPath = 'assets/Logo_PLN.png';
  static const _logoHssePath = 'assets/Logo_Resmi_HSSE_PLN.png';

  static Future<Uint8List> generate({
    required List<TemuanModel> temuan,
    DateTime? startDate,
    DateTime? endDate,
    String? ulpLabel,
    DateTime? generatedAt,
    LogoAssetLoader? logoAssetLoader,
  }) async {
    final createdAt = generatedAt ?? DateTime.now();
    final loader = logoAssetLoader ?? rootBundle.load;
    final logoHsse = await _loadLogo(loader, _logoHssePath);
    final logoPln = await _loadLogo(loader, _logoPlnPath);
    final document = pw.Document();

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(28),
        header:
            (_) => _buildHeader(
              logoHsse: logoHsse,
              logoPln: logoPln,
              startDate: startDate,
              endDate: endDate,
              ulpLabel: ulpLabel,
            ),
        footer:
            (context) => _buildFooter(
              temuan: temuan,
              generatedAt: createdAt,
              pageNumber: context.pageNumber,
              pagesCount: context.pagesCount,
            ),
        build: (_) => [_buildTable(temuan)],
      ),
    );

    return document.save();
  }

  static Future<pw.MemoryImage?> _loadLogo(
    LogoAssetLoader loader,
    String path,
  ) async {
    try {
      final data = await loader(path);
      if (data.lengthInBytes == 0) return null;
      return pw.MemoryImage(
        Uint8List.view(data.buffer, data.offsetInBytes, data.lengthInBytes),
      );
    } catch (_) {
      return null;
    }
  }

  static pw.Widget _buildHeader({
    required pw.MemoryImage? logoHsse,
    required pw.MemoryImage? logoPln,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _logoBox(logoHsse, width: 64, height: 64),
            pw.Expanded(
              child: pw.Column(
                children: [
                  pw.Text(
                    reportTitle,
                    textAlign: pw.TextAlign.center,
                    style: pw.TextStyle(
                      fontSize: 15,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    'Periode: ${_periodLabel(startDate, endDate)}',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                  pw.Text(
                    'ULP: ${_valueOrDash(ulpLabel)}',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ],
              ),
            ),
            _logoBox(logoPln, width: 72, height: 64),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Divider(height: 1, thickness: 0.8),
        pw.SizedBox(height: 12),
      ],
    );
  }

  static pw.Widget _logoBox(
    pw.MemoryImage? image, {
    required double width,
    required double height,
  }) {
    if (image == null) {
      return pw.SizedBox(width: width, height: height);
    }

    return pw.SizedBox(
      width: width,
      height: height,
      child: pw.Image(image, fit: pw.BoxFit.contain),
    );
  }

  static pw.Widget _buildTable(List<TemuanModel> temuan) {
    if (temuan.isEmpty) {
      return pw.Container(
        padding: const pw.EdgeInsets.all(16),
        alignment: pw.Alignment.center,
        child: pw.Text(
          'Tidak ada temuan yang dipilih.',
          style: const pw.TextStyle(fontSize: 10),
        ),
      );
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey500, width: 0.5),
      columnWidths: const {
        0: pw.FixedColumnWidth(22),
        1: pw.FixedColumnWidth(46),
        2: pw.FixedColumnWidth(48),
        3: pw.FixedColumnWidth(34),
        4: pw.FlexColumnWidth(1.5),
        5: pw.FlexColumnWidth(1.45),
        6: pw.FlexColumnWidth(1.25),
        7: pw.FlexColumnWidth(1.1),
        8: pw.FixedColumnWidth(34),
        9: pw.FixedColumnWidth(42),
        10: pw.FlexColumnWidth(1.0),
        11: pw.FixedColumnWidth(48),
        12: pw.FlexColumnWidth(1.05),
      },
      children: [
        _tableRow(
          [
            'No',
            'Tanggal',
            'ULP',
            'Tipe',
            'Alamat Temuan',
            'Lokasi / Maps',
            'Pemilik / Objek',
            'Penyulang',
            'Zona',
            'Section',
            'Risiko',
            'Status',
            'Tindak Lanjut',
          ].map(_headerCell).toList(),
          isHeader: true,
        ),
        for (var i = 0; i < temuan.length; i++)
          _tableRow([
            _bodyCell('${i + 1}', align: pw.Alignment.center),
            _bodyCell(
              _formatDate(temuan[i].tanggalTemuan),
              align: pw.Alignment.center,
            ),
            _bodyCell(_valueOrDash(temuan[i].ulp)),
            _bodyCell(
              _valueOrDash(temuan[i].tipeTemuan),
              align: pw.Alignment.center,
            ),
            _bodyCell(_valueOrDash(temuan[i].alamatTemuan)),
            _locationCell(temuan[i]),
            _bodyCell(_pemilikObjekLabel(temuan[i])),
            _bodyCell(_valueOrDash(temuan[i].namaPenyulang)),
            _bodyCell(
              _valueOrDash(temuan[i].zona?.toString()),
              align: pw.Alignment.center,
            ),
            _bodyCell(
              _valueOrDash(temuan[i].section?.toString()),
              align: pw.Alignment.center,
            ),
            _bodyCell(_risikoLabel(temuan[i])),
            _bodyCell(_valueOrDash(temuan[i].statusTemuan)),
            _bodyCell(_tindakLanjutLabel(temuan[i])),
          ]),
      ],
    );
  }

  static pw.TableRow _tableRow(
    List<pw.Widget> children, {
    bool isHeader = false,
  }) {
    return pw.TableRow(
      decoration:
          isHeader
              ? const pw.BoxDecoration(color: PdfColors.blueGrey800)
              : null,
      children: children,
    );
  }

  static pw.Widget _headerCell(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 5),
      alignment: pw.Alignment.center,
      child: pw.Text(
        text,
        textAlign: pw.TextAlign.center,
        style: pw.TextStyle(
          color: PdfColors.white,
          fontSize: 6.3,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  static pw.Widget _bodyCell(
    String text, {
    pw.Alignment align = pw.Alignment.centerLeft,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 4),
      alignment: align,
      child: pw.Text(text, style: const pw.TextStyle(fontSize: 5.8)),
    );
  }

  static pw.Widget _locationCell(TemuanModel item) {
    final latitude = item.latitude;
    final longitude = item.longitude;
    final coordinates =
        latitude == null || longitude == null ? '' : '$latitude, $longitude';

    if (latitude == null || longitude == null) {
      return _bodyCell(_valueOrDash(item.lokasi));
    }

    final url =
        'https://www.google.com/maps/search/?api=1&query=$latitude,$longitude';

    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 4),
      alignment: pw.Alignment.centerLeft,
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.UrlLink(
            destination: url,
            child: pw.Text(
              'Buka Maps',
              style: const pw.TextStyle(
                fontSize: 5.8,
                color: PdfColors.blue700,
                decoration: pw.TextDecoration.underline,
              ),
            ),
          ),
          pw.SizedBox(height: 1.5),
          pw.Text(
            coordinates,
            style: const pw.TextStyle(fontSize: 5.2, color: PdfColors.grey700),
          ),
        ],
      ),
    );
  }

  static String _pemilikObjekLabel(TemuanModel item) {
    return _joinNonEmpty([item.namaPemilik, item.jenisObjek, item.jenisAset]);
  }

  static String _risikoLabel(TemuanModel item) {
    final score = item.skorMatriks == null ? null : 'Skor ${item.skorMatriks}';
    return _joinNonEmpty([
      item.levelRisiko,
      score,
      item.jarakAktivitas,
      item.intensitasAktivitas,
    ]);
  }

  static String _tindakLanjutLabel(TemuanModel item) {
    if (item.tglClosing != null) {
      return 'Closed: ${_formatDate(item.tglClosing!)}';
    }
    if (item.tglReminder != null) {
      return 'Reminder: ${_formatDate(item.tglReminder!)}';
    }
    return '-';
  }

  static String _joinNonEmpty(List<String?> values) {
    final filtered =
        values
            .where((value) => value != null && value.trim().isNotEmpty)
            .map((value) => value!.trim())
            .toList();
    if (filtered.isEmpty) return '-';
    return filtered.join(' / ');
  }

  static pw.Widget _buildFooter({
    required List<TemuanModel> temuan,
    required DateTime generatedAt,
    required int pageNumber,
    required int pagesCount,
  }) {
    final statusCounts = <String, int>{};
    for (final item in temuan) {
      final status = _valueOrDash(item.statusTemuan);
      statusCounts[status] = (statusCounts[status] ?? 0) + 1;
    }
    final breakdown = statusCounts.entries
        .map((entry) => '${entry.key}: ${entry.value}')
        .join(' | ');

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.SizedBox(height: 8),
        pw.Divider(height: 1, thickness: 0.6),
        pw.SizedBox(height: 6),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Expanded(
              child: pw.Text(
                'Total temuan: ${temuan.length}'
                '${breakdown.isEmpty ? '' : ' | $breakdown'}',
                style: const pw.TextStyle(fontSize: 8),
              ),
            ),
            pw.SizedBox(width: 12),
            pw.Text(
              'Generate: ${_formatDateTime(generatedAt)} | Halaman $pageNumber/$pagesCount',
              style: const pw.TextStyle(fontSize: 8),
            ),
          ],
        ),
      ],
    );
  }

  static String _periodLabel(DateTime? startDate, DateTime? endDate) {
    if (startDate == null && endDate == null) return 'Semua periode';
    if (startDate != null && endDate != null) {
      return '${_formatDate(startDate)} - ${_formatDate(endDate)}';
    }
    if (startDate != null) return 'Mulai ${_formatDate(startDate)}';
    return 'Sampai ${_formatDate(endDate!)}';
  }

  static String _formatDate(DateTime date) {
    final day = date.day.toString().padLeft(2, '0');
    final month = date.month.toString().padLeft(2, '0');
    return '$day/$month/${date.year}';
  }

  static String _formatDateTime(DateTime date) {
    final hour = date.hour.toString().padLeft(2, '0');
    final minute = date.minute.toString().padLeft(2, '0');
    return '${_formatDate(date)} $hour:$minute';
  }

  static String _valueOrDash(String? value) {
    if (value == null || value.trim().isEmpty) return '-';
    return value;
  }
}
