import 'dart:typed_data';

import 'package:flutter/services.dart' show ByteData, rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../config/temuan_model.dart';

typedef LogoAssetLoader = Future<ByteData> Function(String path);

class ExportTemuanPdfGenerator {
  static const reportTitle = 'TEMUAN POTENSI KMU / ROW - GENERATED BY ELSAFE';

  static const _logoPlnPath = 'assets/Logo_PLN.png';
  static const _logoHssePath = 'assets/Logo_HSSE_PLN.png';

  static Future<Uint8List> generate({
    required List<TemuanModel> temuan,
    DateTime? startDate,
    DateTime? endDate,
    String? ulpLabel,
    DateTime? generatedAt,
    LogoAssetLoader? logoAssetLoader,
  }) async {
    final createdAt = generatedAt ?? DateTime.now();
    final loader = logoAssetLoader ?? rootBundle.load;
    final logoHsse = await _loadLogo(loader, _logoHssePath);
    final logoPln = await _loadLogo(loader, _logoPlnPath);
    final document = pw.Document();

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(28),
        header:
            (_) => _buildHeader(
              logoHsse: logoHsse,
              logoPln: logoPln,
              startDate: startDate,
              endDate: endDate,
              ulpLabel: ulpLabel,
            ),
        footer:
            (context) => _buildFooter(
              temuan: temuan,
              generatedAt: createdAt,
              pageNumber: context.pageNumber,
              pagesCount: context.pagesCount,
            ),
        build: (_) => [_buildTable(temuan)],
      ),
    );

    return document.save();
  }

  static Future<pw.MemoryImage?> _loadLogo(
    LogoAssetLoader loader,
    String path,
  ) async {
    try {
      final data = await loader(path);
      if (data.lengthInBytes == 0) return null;
      return pw.MemoryImage(
        Uint8List.view(data.buffer, data.offsetInBytes, data.lengthInBytes),
      );
    } catch (_) {
      return null;
    }
  }

  static pw.Widget _buildHeader({
    required pw.MemoryImage? logoHsse,
    required pw.MemoryImage? logoPln,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? ulpLabel,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _logoBox(logoHsse),
            pw.Expanded(
              child: pw.Column(
                children: [
                  pw.Text(
                    reportTitle,
                    textAlign: pw.TextAlign.center,
                    style: pw.TextStyle(
                      fontSize: 15,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    'Periode: ${_periodLabel(startDate, endDate)}',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                  pw.Text(
                    'ULP: ${_valueOrDash(ulpLabel)}',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ],
              ),
            ),
            _logoBox(logoPln),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Divider(height: 1, thickness: 0.8),
        pw.SizedBox(height: 12),
      ],
    );
  }

  static pw.Widget _logoBox(pw.MemoryImage? image) {
    if (image == null) {
      return pw.SizedBox(width: 72, height: 42);
    }

    return pw.SizedBox(
      width: 72,
      height: 42,
      child: pw.Image(image, fit: pw.BoxFit.contain),
    );
  }

  static pw.Widget _buildTable(List<TemuanModel> temuan) {
    final rows = <List<String>>[
      for (var i = 0; i < temuan.length; i++)
        [
          '${i + 1}',
          _formatDate(temuan[i].tanggalTemuan),
          temuan[i].lokasi,
          _valueOrDash(temuan[i].namaPenyulang),
          _valueOrDash(temuan[i].zona?.toString()),
          _valueOrDash(temuan[i].section?.toString()),
          _valueOrDash(temuan[i].statusTemuan),
          _valueOrDash(temuan[i].levelRisiko),
        ],
    ];

    if (rows.isEmpty) {
      return pw.Container(
        padding: const pw.EdgeInsets.all(16),
        alignment: pw.Alignment.center,
        child: pw.Text(
          'Tidak ada temuan yang dipilih.',
          style: const pw.TextStyle(fontSize: 10),
        ),
      );
    }

    return pw.TableHelper.fromTextArray(
      headers: const [
        'No',
        'Tanggal',
        'Lokasi',
        'Penyulang',
        'Zona',
        'Section',
        'Status',
        'Level Risiko',
      ],
      data: rows,
      border: pw.TableBorder.all(color: PdfColors.grey500, width: 0.5),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey800),
      headerStyle: pw.TextStyle(
        color: PdfColors.white,
        fontSize: 8,
        fontWeight: pw.FontWeight.bold,
      ),
      cellStyle: const pw.TextStyle(fontSize: 7),
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
      columnWidths: const {
        0: pw.FixedColumnWidth(24),
        1: pw.FixedColumnWidth(52),
        2: pw.FlexColumnWidth(2.2),
        3: pw.FlexColumnWidth(1.4),
        4: pw.FixedColumnWidth(38),
        5: pw.FixedColumnWidth(46),
        6: pw.FixedColumnWidth(62),
        7: pw.FixedColumnWidth(68),
      },
      cellAlignments: const {
        0: pw.Alignment.center,
        1: pw.Alignment.center,
        4: pw.Alignment.center,
        5: pw.Alignment.center,
      },
    );
  }

  static pw.Widget _buildFooter({
    required List<TemuanModel> temuan,
    required DateTime generatedAt,
    required int pageNumber,
    required int pagesCount,
  }) {
    final statusCounts = <String, int>{};
    for (final item in temuan) {
      final status = _valueOrDash(item.statusTemuan);
      statusCounts[status] = (statusCounts[status] ?? 0) + 1;
    }
    final breakdown = statusCounts.entries
        .map((entry) => '${entry.key}: ${entry.value}')
        .join(' | ');

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.SizedBox(height: 8),
        pw.Divider(height: 1, thickness: 0.6),
        pw.SizedBox(height: 6),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Expanded(
              child: pw.Text(
                'Total temuan: ${temuan.length}'
                '${breakdown.isEmpty ? '' : ' | $breakdown'}',
                style: const pw.TextStyle(fontSize: 8),
              ),
            ),
            pw.SizedBox(width: 12),
            pw.Text(
              'Generate: ${_formatDateTime(generatedAt)} | Halaman $pageNumber/$pagesCount',
              style: const pw.TextStyle(fontSize: 8),
            ),
          ],
        ),
      ],
    );
  }

  static String _periodLabel(DateTime? startDate, DateTime? endDate) {
    if (startDate == null && endDate == null) return 'Semua periode';
    if (startDate != null && endDate != null) {
      return '${_formatDate(startDate)} - ${_formatDate(endDate)}';
    }
    if (startDate != null) return 'Mulai ${_formatDate(startDate)}';
    return 'Sampai ${_formatDate(endDate!)}';
  }

  static String _formatDate(DateTime date) {
    final day = date.day.toString().padLeft(2, '0');
    final month = date.month.toString().padLeft(2, '0');
    return '$day/$month/${date.year}';
  }

  static String _formatDateTime(DateTime date) {
    final hour = date.hour.toString().padLeft(2, '0');
    final minute = date.minute.toString().padLeft(2, '0');
    return '${_formatDate(date)} $hour:$minute';
  }

  static String _valueOrDash(String? value) {
    if (value == null || value.trim().isEmpty) return '-';
    return value;
  }
}
